# Generated by Django 5.1.3 on 2024-12-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SportsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                ("game_datetime", models.DateTimeField(verbose_name="Game Time")),
                (
                    "observation_datetime",
                    models.DateTimeField(verbose_name="Last Updated"),
                ),
                ("league", models.CharField(max_length=255, verbose_name="League")),
                (
                    "home_team",
                    models.CharField(max_length=255, verbose_name="Home Team"),
                ),
                (
                    "away_team",
                    models.CharField(max_length=255, verbose_name="Away Team"),
                ),
                (
                    "home_win_prob",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        verbose_name="Home Win Probability",
                    ),
                ),
                (
                    "away_win_prob",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        verbose_name="Away Win Probability",
                    ),
                ),
                ("win_prob_history", models.JSONField(blank=True, null=True)),
                ("closed", models.BooleanField(default=False)),
                ("settled", models.BooleanField(default=False)),
                (
                    "home_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Home Score"
                    ),
                ),
                (
                    "away_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Away Score"
                    ),
                ),
                (
                    "winning_team",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Winner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BettingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_datetime",
                    models.DateTimeField(verbose_name="Last Updated"),
                ),
                (
                    "sportsbook",
                    models.CharField(max_length=255, verbose_name="Sportsbook"),
                ),
                ("side", models.CharField(max_length=255, verbose_name="Side")),
                (
                    "hit_prob",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Hit Probability"
                    ),
                ),
                (
                    "odds",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Odds"
                    ),
                ),
                (
                    "expected_roi",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Expected ROI"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betting_lines",
                        to="moneyline_dashboard.sportsevent",
                    ),
                ),
            ],
        ),
    ]
