# Generated by Django 5.1.3 on 2024-12-08 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyline_dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "bankroll",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Bankroll"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sportsbook",
                    models.CharField(max_length=255, verbose_name="Sportsbook"),
                ),
                ("side", models.CharField(max_length=255, verbose_name="Side")),
                (
                    "odds",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Odds"
                    ),
                ),
                (
                    "stake",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Stake"
                    ),
                ),
                (
                    "original_hit_prob",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("closed", models.BooleanField(default=False)),
                (
                    "closing_hit_prob",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                ("settled", models.BooleanField(default=False)),
                ("hit", models.BooleanField(default=False)),
                (
                    "net_payout",
                    models.DecimalField(decimal_places=6, max_digits=10, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wager_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wager_game",
                        to="moneyline_dashboard.sportsevent",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wager_portfolio",
                        to="moneyline_dashboard.portfolio",
                    ),
                ),
            ],
        ),
    ]
