# Generated by Django 5.1.3 on 2024-12-08 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneyline_dashboard", "0002_portfolio_wager"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="original_bankroll",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Original Bankroll",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="bankroll",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, null=True, verbose_name="Bankroll"
            ),
        ),
    ]
